export const GPSS_BLOCK_ICON_SHAPES: Record<string, string> = {
  ADOPT: 'rect',
  ADVANCE: 'rect',
  ALTER: 'rect',
  ASSEMBLE: 'assemble',
  ASSIGN: 'assign',
  BUFFER: 'buffer',
  CLOSE: 'rect',
  COUNT: 'test',
  DEPART: 'depart',
  DISPLACE: 'rect',
  ENTER: 'enter',
  EXAMINE: 'test',
  EXECUTE: 'rect',
  FAVAIL: 'rect',
  FUNAVAIL: 'rect',
  GATE: 'diamond',
  GATHER: 'gather',
  GENERATE: 'generate',
  INDEX: 'test',
  JOIN: 'gather',
  LEAVE: 'leave',
  LINK: 'link',
  LOGIC: 'logic',
  LOOP: 'loop',
  MARK: 'mark',
  MATCH: 'match',
  MSAVEVALUE: 'savevalue',
  OPEN: 'rect',
  PREEMPT: 'preempt',
  PRIORITY: 'priority',
  QUEUE: 'queue',
  READ: 'rect',
  RELEASE: 'release',
  REMOVE: 'rect',
  RETURN: 'return',
  SAVAIL: 'rect',
  SAVEVALUE: 'savevalue',
  SCAN: 'test',
  SEEK: 'test',
  SEIZE: 'seize',
  SELECT: 'select',
  SPLIT: 'rect',
  SUNAVAIL: 'rect',
  TABULATE: 'tabulate',
  TERMINATE: 'terminate',
  TEST: 'test',
  TRANSFER: 'diamond',
  UNLINK: 'unlink',
  WRITE: 'rect',
};

export const GPSS_GALLERY_BLOCKS = [
  'ADVANCE',
  'ASSEMBLE',
  'ASSIGN',
  'BUFFER',
  'DEPART',
  'ENTER',
  'GATE',
  'GATHER',
  'GENERATE',
  'LEAVE',
  'LINK',
  'LOGIC',
  'LOOP',
  'MARK',
  'MATCH',
  'MSAVEVALUE',
  'PREEMPT',
  'PRIORITY',
  'QUEUE',
  'RELEASE',
  'RETURN',
  'SAVEVALUE',
  'SEIZE',
  'SELECT',
  'SPLIT',
  'TABULATE',
  'TERMINATE',
  'TEST',
  'TRANSFER',
  'UNLINK',
] as const;

export function getGpssBlockIconShape(blockName: string): string {
  return GPSS_BLOCK_ICON_SHAPES[blockName.toUpperCase()] ?? 'rect';
}
